// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tides.Core.Domain.ValueObjects;
using Tides.Infrastructure.Persistence;

#nullable disable

namespace Tides.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TidesDbContext))]
    partial class TidesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tides.Core.Domain.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("Tides.Core.Domain.Carnival", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("HostingClubId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Sanction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("HostingClubId");

                    b.ToTable("carnivals", (string)null);
                });

            modelBuilder.Entity("Tides.Core.Domain.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("clubs", (string)null);
                });

            modelBuilder.Entity("Tides.Core.Domain.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HeatId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsWithdrawn")
                        .HasColumnType("boolean");

                    b.Property<int?>("Lane")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string>("MemberIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("EventDefinitionId");

                    b.HasIndex("HeatId");

                    b.ToTable("entries", (string)null);
                });

            modelBuilder.Entity("Tides.Core.Domain.EventDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AdvanceFastestN")
                        .HasColumnType("integer");

                    b.Property<int>("AdvanceTopN")
                        .HasColumnType("integer");

                    b.Property<string>("AdvancementRule")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("AgeGroup")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("CarnivalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("MaxLanes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CarnivalId");

                    b.HasIndex("CarnivalId", "AgeGroup", "Category", "Gender");

                    b.ToTable("event_definitions", (string)null);
                });

            modelBuilder.Entity("Tides.Core.Domain.Heat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("HeatNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable("heats", (string)null);
                });

            modelBuilder.Entity("Tides.Core.Domain.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SurfguardId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("SurfguardId")
                        .IsUnique()
                        .HasFilter("\"SurfguardId\" IS NOT NULL");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("Tides.Core.Domain.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("organisations", (string)null);
                });

            modelBuilder.Entity("Tides.Core.Domain.PointsTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CarnivalId")
                        .HasColumnType("uuid");

                    b.Property<IReadOnlyList<PointsTableEntry>>("Entries")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("entries");

                    b.Property<bool>("FractionalTiesEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CarnivalId")
                        .IsUnique();

                    b.ToTable("points_tables", (string)null);
                });

            modelBuilder.Entity("Tides.Core.Domain.Protest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AdjudicatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AdjudicationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("CarnivalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("HeatId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LodgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LodgedByClubId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CarnivalId");

                    b.HasIndex("EventId");

                    b.ToTable("protests", (string)null);
                });

            modelBuilder.Entity("Tides.Core.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganisationId");

                    b.ToTable("regions", (string)null);
                });

            modelBuilder.Entity("Tides.Core.Domain.Result", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<IReadOnlyList<AuditEntry>>("AuditTrail")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("audit_trail");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HeatId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("JudgeScore")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Placing", "Tides.Core.Domain.Result.Placing#Placing", b1 =>
                        {
                            b1.Property<int>("Position")
                                .HasColumnType("integer")
                                .HasColumnName("placing");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Time", "Tides.Core.Domain.Result.Time#TimeResult", b1 =>
                        {
                            b1.Property<TimeSpan>("Time")
                                .HasColumnType("interval")
                                .HasColumnName("time");
                        });

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.HasIndex("HeatId");

                    b.ToTable("results", (string)null);
                });

            modelBuilder.Entity("Tides.Core.Domain.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("EventDefinitionId");

                    b.ToTable("rounds", (string)null);
                });

            modelBuilder.Entity("Tides.Core.Domain.Entry", b =>
                {
                    b.HasOne("Tides.Core.Domain.Heat", null)
                        .WithMany("Entries")
                        .HasForeignKey("HeatId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Tides.Core.Domain.EventDefinition", b =>
                {
                    b.HasOne("Tides.Core.Domain.Carnival", null)
                        .WithMany("Events")
                        .HasForeignKey("CarnivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tides.Core.Domain.Heat", b =>
                {
                    b.HasOne("Tides.Core.Domain.Round", null)
                        .WithMany("Heats")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tides.Core.Domain.PointsTable", b =>
                {
                    b.HasOne("Tides.Core.Domain.Carnival", null)
                        .WithOne("PointsTable")
                        .HasForeignKey("Tides.Core.Domain.PointsTable", "CarnivalId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Tides.Core.Domain.Protest", b =>
                {
                    b.HasOne("Tides.Core.Domain.Carnival", null)
                        .WithMany("Protests")
                        .HasForeignKey("CarnivalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tides.Core.Domain.Result", b =>
                {
                    b.HasOne("Tides.Core.Domain.Heat", null)
                        .WithMany("Results")
                        .HasForeignKey("HeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tides.Core.Domain.Round", b =>
                {
                    b.HasOne("Tides.Core.Domain.EventDefinition", null)
                        .WithMany("Rounds")
                        .HasForeignKey("EventDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tides.Core.Domain.Carnival", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("PointsTable");

                    b.Navigation("Protests");
                });

            modelBuilder.Entity("Tides.Core.Domain.EventDefinition", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("Tides.Core.Domain.Heat", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("Tides.Core.Domain.Round", b =>
                {
                    b.Navigation("Heats");
                });
#pragma warning restore 612, 618
        }
    }
}
